require("scene")
require("gameobject")
require("physics")
require("light")
require("camera")
require("ui")

function setup(scene, object)
    test = ui_element_create(scene, nil)
    ui_element_size(test, 0.2, 0.1)
    ui_element_allign(test, "left", 0)
    ui_element_allign(test, "bottom", 0.1)
    ui_element_set_text(test, "test some very very very long text")
    ui_element_set_text_allign(test, "center")
    --test2 = ui_element_create(scene, test)
    --ui_element_size(test2, 1, 0.1)
    --ui_element_move(test2, 1, 0)

    example = scene_add_gameobject(scene)
    gameobject_transform(example, 0, 0, 0)
    scene_set_model(scene, example, "track_1.dae")
    scene_set_texture(scene, example, "track_albedo.png")
    scene_set_normal(scene, example, "track_normal.png")
    scene_set_pbr(scene, example, "track_pbr.png")
    physics_init_mesh(scene, example, 0)

    ship = scene_add_gameobject(scene)
    gameobject_transform(ship, 0, 1.2, 0)
    scene_add_script(scene, ship, "ship.lua")

    sun = scene_add_light(scene)
    scene_enable_shadow(scene, sun)
    sun_cam = light_get_camera(sun)
    camera_set_fov(sun, -1)
    camera_set_size(sun, 10, 10)
    sun_obj = camera_get_gameobject(sun_cam)
    gameobject_rotate(sun_obj, -math.pi/4.0, 0.0, 0.0)
    gameobject_transform(sun_obj, 0, 10, 10)
    gameobject_set_integer(sun_obj, "target", ship)
    scene_add_script(scene, sun_obj, "sun.lua")
end
